Teams:
  Red:
    - "Player1"
  Yellow:
    - "Player2"
  Blue:
  Green:
  Black:
  White:
  Brown:
  Orange:
  Cyan:
  Purple:
  Gray:
  Light_Blue:
  Pink:
  Lime:
  Magenta:
  Silver: